import React, { createContext, useContext, useEffect, useState } from "react";
import AsyncStorage from "@react-native-async-storage/async-storage";

export interface LanguageOption {
  code: string;
  name: string;
  nativeName: string;
}

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: "en", name: "English", nativeName: "English" },
  { code: "hi", name: "Hindi", nativeName: "हिंदी" },
  { code: "or", name: "Odia", nativeName: "ଓଡ଼ିଆ" },
  { code: "te", name: "Telugu", nativeName: "తెలుగు" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা" },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்" },
  { code: "mr", name: "Marathi", nativeName: "मराठी" },
  { code: "gu", name: "Gujarati", nativeName: "ગુજરાતી" },
];

export const translations: Record<string, Record<string, string>> = {
  en: {
    // Navigation & Tabs
    home: "Home",
    progress: "Progress",
    schedule: "Schedule",
    tasks: "Tasks",
    aiAssistant: "AI Assistant",
    profile: "Profile",
    messages: "Messages",
    message: "Message",

    // Common
    settings: "Settings",
    search: "Search...",
    viewAll: "View All",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    loading: "Loading...",
    success: "Success",
    error: "Error",

    // Home Dashboard
    welcomeBack: "Welcome back",
    services: "Services",
    quickStats: "Quick Stats",
    todaySchedule: "Today's Schedule",
    recentNotices: "Recent Notices",
    attendance: "Attendance",
    studyHours: "Study Hours",
    assignments: "Assignments",
    cgpa: "CGPA",
    tasksDone: "Tasks Done",

    // Services
    fees: "Fees",
    hostel: "Hostel",
    mess: "Mess",
    notice: "Notice",
    notices: "Notices",
    report: "Report",
    reports: "Reports",
    faculty: "Faculty",
    faculties: "Faculty Directory",
    request: "Request",
    requests: "Requests",
    complaint: "Complaint",
    complaints: "Complaints",
    submitComplaint: "Submit Complaint",
    bonafideCertificate: "Bonafide Certificate",
    documents: "Documents",
    docRequest: "Certificates / Forms",
    gatePass: "Gate Pass",
    more: "More",
    leaveRequest: "Leave Request",
    feeDuesQuery: "Fee/Dues Query",
    pending: "Pending",
    approved: "Approved",
    inProgress: "In Progress",
    resolved: "Resolved",
    confirmed: "Confirmed",
    confirmResolution: "Confirm Resolution",
    auditTrail: "Audit Trail",
    assignedStaff: "Assigned Staff",
    location: "Location",

    // Progress Screen
    yourProgress: "YOUR PROGRESS 📊",
    academicJourney: "Track your academic journey",
    weeklyStudyTime: "Weekly Study Time",
    classesAttended: "Classes Attended",
    testsTaken: "Tests Taken",
    studyStreak: "Study Streak",
    subjectWiseProgress: "Subject-wise Progress",
    thisWeekActivity: "This Week Activity Summary",

    // Schedule Screen
    yourSchedule: "YOUR SCHEDULE 🗓️",
    manageTimetable: "Organize your day efficiently",
    addClass: "Add Class",
    saveClass: "Save Class",
    startTime: "Start Time",
    endTime: "End Time",
    room: "Room",
    facultyName: "Faculty",
    completed: "Completed",
    ongoing: "Ongoing",
    upcoming: "Upcoming",
    tomorrow: "Tomorrow",
    manageSubjects: "Manage Subjects",

    // Tasks Screen
    stayProductive: "STAY PRODUCTIVE 🛡️",
    neverMissDeadline: "Never miss a deadline",
    all: "All",
    toDo: "To Do",
    addTask: "Add Task",
    subject: "Subject",
    due: "Due",
    priority: "Priority",
    subtasks: "Subtasks",

    // Settings
    account: "Account",
    editProfile: "Edit Profile",
    password: "Password",
    changePassword: "Change Password",
    notifications: "Notifications",
    preferences: "Preferences",
    theme: "Theme",
    language: "Language",
    college: "College",
    accountRole: "Account Role",
    student: "Student",
    academicDetails: "Academic Details",
    support: "Support",
    helpFaq: "Help & FAQ",
    logout: "Logout",
    loggingOut: "Logging out...",
    chooseTheme: "Choose Theme",
    chooseLanguage: "Choose Language",
    light: "Light",
    dark: "Dark",
    system: "System",
    currentPassword: "Current password",
    newPassword: "New password",
    confirmPassword: "Confirm new password",
    passwordHint: "Password must be at least 6 characters.",
    passwordMismatch: "New password and confirmation do not match.",
    passwordWeak: "Your new password must be at least 6 characters.",
    passwordSame: "Your new password must be different from current password.",
    missingInfo: "Please fill in all password fields.",
    updating: "Updating...",
    forgotPasswordPrompt: "Forgot current password?",
    sendResetEmail: "Send Reset Link to Email",
    resetEmailSent: "Password Reset Email Sent",
    resetEmailSentDesc: "A password reset link has been sent to your registered email. Please check your inbox.",
    passwordChangedSuccess: "Your password has been updated successfully.",
    notLoggedIn: "You are not logged in. Please log in first.",
    learnConnectGrow: "Learn. Connect. Grow.",
    collegeSubtext: "Everything you need for your college life in one place.",
    attendanceGood: "Your attendance is good!",
    targetReached: "of daily goal",
    cgpaStatus: "Overall performance",
    leaveGatepass: "Leave / Pass",
    specialNotes: "Special Notes & Important Questions",
    specialNotesSub: "Important questions, exam notes and revision tips from faculty",
    teacherPortal: "Teacher Portal (Update ID & Password)",
    teacherConnection: "Teacher & Classroom Connection",
    connectTeacher: "Connect with Teacher (Join Class)",
    teacherMessages: "Teacher Messages & Photos",
    attendanceStanding: "Attendance & Standing",
    studentInfo: "Student Information",
    degree: "Degree",
    department: "Department",
    semester: "Semester",
    section: "Section",
    rollNo: "Roll Number",
    certificatesHonors: "Certificates & Honors",
    academicTimetable: "Academic Timetable",
    personalInfo: "Personal Information",
    fullName: "Full Name",
    email: "Email",
    phoneNumber: "Phone Number",
  },
  hi: {
    // Navigation & Tabs
    home: "होम",
    progress: "प्रगति",
    schedule: "समय सारिणी",
    tasks: "कार्य",
    aiAssistant: "एआई सहायक",
    profile: "प्रोफ़ाइल",
    messages: "संदेश",
    message: "संदेश",

    // Common
    settings: "सेटिंग्स",
    search: "खोजें...",
    viewAll: "सभी देखें",
    save: "सहेजें",
    cancel: "रद्द करें",
    delete: "हटाएं",
    loading: "लोड हो रहा है...",
    success: "सफल",
    error: "त्रुटि",

    // Home Dashboard
    welcomeBack: "स्वागत है",
    services: "सेवाएं",
    quickStats: "त्वरित आँकड़े",
    todaySchedule: "आज की समय सारिणी",
    recentNotices: "ताज़ा सूचनाएं",
    attendance: "उपस्थिति",
    studyHours: "अध्ययन के घंटे",
    assignments: "असाइनमेंट",
    cgpa: "सीजीपीए",
    tasksDone: "पूर्ण कार्य",

    // Services
    fees: "शुल्क",
    hostel: "छात्रावास",
    mess: "मेस",
    notice: "सूचना",
    notices: "सूचनाएं",
    report: "रिपोर्ट",
    reports: "रिपोर्ट्स",
    faculty: "संकाय",
    faculties: "संकाय निर्देशिका",
    request: "अनुरोध",
    more: "अधिक",

    // Progress Screen
    yourProgress: "आपकी प्रगति 📊",
    academicJourney: "अपनी शैक्षणिक यात्रा पर नज़र रखें",
    weeklyStudyTime: "साप्ताहिक अध्ययन समय",
    classesAttended: "उपस्थित कक्षाएं",
    testsTaken: "दिए गए टेस्ट",
    studyStreak: "अध्ययन सिलसिला",
    subjectWiseProgress: "विषय-वार प्रगति",
    thisWeekActivity: "इस सप्ताह गतिविधि सारांश",

    // Schedule Screen
    yourSchedule: "आपकी समय सारिणी 🗓️",
    manageTimetable: "अपने दिन को कुशलतापूर्वक व्यवस्थित करें",
    addClass: "कक्षा जोड़ें",
    saveClass: "कक्षा सहेजें",
    startTime: "शुरुआत का समय",
    endTime: "समाप्ति समय",
    room: "कमरा",
    facultyName: "अध्यापक / संकाय",
    completed: "पूर्ण",
    ongoing: "जारी",
    upcoming: "आगामी",
    tomorrow: "कल",
    manageSubjects: "विषय प्रबंधित करें",

    // Tasks Screen
    stayProductive: "उत्पादक रहें 🛡️",
    neverMissDeadline: "कोई भी समय सीमा न चूकें",
    all: "सभी",
    toDo: "करने योग्य",
    inProgress: "प्रगति पर",
    addTask: "कार्य जोड़ें",
    subject: "विषय",
    due: "नियत तारीख",
    priority: "प्राथमिकता",
    subtasks: "उप-कार्य",

    // Settings
    account: "खाता",
    editProfile: "प्रोफ़ाइल संपादित करें",
    password: "पासवर्ड",
    changePassword: "पासवर्ड बदलें",
    notifications: "सूचनाएं",
    preferences: "प्राथमिकताएं",
    theme: "थीम",
    language: "भाषा",
    college: "कॉलेज",
    accountRole: "खाता भूमिका",
    student: "छात्र",
    academicDetails: "शैक्षणिक विवरण",
    support: "सहायता",
    helpFaq: "मदद और अक्सर पूछे जाने वाले प्रश्न",
    logout: "लॉग आउट",
    loggingOut: "लॉग आउट हो रहा है...",
    chooseTheme: "थीम चुनें",
    chooseLanguage: "भाषा चुनें",
    light: "लाइट",
    dark: "डार्क",
    system: "सिस्टम",
    currentPassword: "वर्तमान पासवर्ड",
    newPassword: "नया पासवर्ड",
    confirmPassword: "नए पासवर्ड की पुष्टि करें",
    passwordHint: "पासवर्ड कम से कम 6 अक्षरों का होना चाहिए।",
    passwordMismatch: "नया पासवर्ड और पुष्टि मेल नहीं खाते।",
    passwordWeak: "नया पासवर्ड कम से कम 6 अक्षरों का होना चाहिए।",
    passwordSame: "नया पासवर्ड वर्तमान पासवर्ड से अलग होना चाहिए।",
    missingInfo: "कृपया सभी पासवर्ड फ़ील्ड भरें।",
    updating: "अपडेट हो रहा है...",
    forgotPasswordPrompt: "वर्तमान पासवर्ड भूल गए?",
    sendResetEmail: "ईमेल पर पासवर्ड रीसेट लिंक भेजें",
    resetEmailSent: "पासवर्ड रीसेट ईमेल भेजा गया",
    resetEmailSentDesc: "आपके पंजीकृत ईमेल पर पासवर्ड रीसेट लिंक भेज दिया गया है।",
    passwordChangedSuccess: "आपका पासवर्ड सफलतापूर्वक अपडेट कर दिया गया है।",
    notLoggedIn: "आप लॉग इन नहीं हैं।",
    learnConnectGrow: "सीखें। जुड़ें। बढ़ें।",
    collegeSubtext: "कॉलेज जीवन के लिए आपकी सभी ज़रूरतें एक ही जगह।",
    attendanceGood: "आपकी उपस्थिति अच्छी है!",
    targetReached: "दैनिक लक्ष्य का",
    cgpaStatus: "समग्र प्रदर्शन",
    leaveGatepass: "अवकाश / पास",
    specialNotes: "विशेष नोट्स और महत्वपूर्ण प्रश्न",
    specialNotesSub: "अध्यापकों द्वारा साझा किए गए महत्वपूर्ण प्रश्न और परीक्षा नोट्स",
    teacherPortal: "अध्यापक पोर्टल (आईडी और पासवर्ड अपडेट)",
    teacherConnection: "शिक्षक और कक्षा संपर्क",
    connectTeacher: "शिक्षक से जुड़ें (कक्षा में शामिल हों)",
    teacherMessages: "शिक्षक संदेश और फोटो",
    attendanceStanding: "उपस्थिति और शैक्षणिक स्थिति",
    studentInfo: "छात्र जानकारी",
    degree: "डिग्री / पाठ्यक्रम",
    department: "विभाग",
    semester: "सत्र / सेमेस्टर",
    section: "अनुभाग / सेक्शन",
    rollNo: "रोल नंबर",
    certificatesHonors: "प्रमाण पत्र और सम्मान",
    academicTimetable: "शैक्षणिक समय सारिणी",
    personalInfo: "व्यक्तिगत जानकारी",
    fullName: "पूरा नाम",
    email: "ईमेल",
    phoneNumber: "फ़ोन नंबर",
  },
  or: {
    // Navigation & Tabs
    home: "ହୋମ୍",
    progress: "ପ୍ରଗତି",
    schedule: "ସମୟ ସାରଣୀ",
    tasks: "କାର୍ଯ୍ୟ",
    profile: "ପ୍ରୋଫାଇଲ୍",

    // Common
    settings: "ସେଟିଂସ",
    search: "ଖୋଜନ୍ତୁ...",
    viewAll: "ସବୁ ଦେଖନ୍ତୁ",
    save: "ସେଭ୍ କରନ୍ତୁ",
    cancel: "ବାତିଲ କରନ୍ତୁ",
    delete: "ଡିଲିଟ୍",
    loading: "ଲୋଡ୍ ହେଉଛି...",
    success: "ସଫଳ",
    error: "ତ୍ରୁଟି",

    // Home Dashboard
    welcomeBack: "ସ୍ୱାଗତ",
    services: "ସେବାସମୂହ",
    quickStats: "ଶୀଘ୍ର ପରିସଂଖ୍ୟାନ",
    todaySchedule: "ଆଜିର ସମୟସାରଣୀ",
    recentNotices: "ନୂତନ ବିଜ୍ଞପ୍ତି",
    attendance: "ଉପସ୍ଥାନ",
    studyHours: "ଅଧ୍ୟୟନ ସମୟ",
    assignments: "ଅସାଇନମେଣ୍ଟ",
    cgpa: "ସିଜିପିଏ",
    tasksDone: "ସମାପ୍ତ କାର୍ଯ୍ୟ",

    // Services
    fees: "ଫିସ",
    hostel: "ଛାତ୍ରାବାସ",
    mess: "ମେସ୍",
    notice: "ବିଜ୍ଞପ୍ତି",
    notices: "ସମସ୍ତ ବିଜ୍ଞପ୍ତି",
    report: "ରିପୋର୍ଟ",
    reports: "ରିପୋର୍ଟସ",
    faculty: "ଶିକ୍ଷକ / ଫ୍ୟାକଲ୍ଟି",
    faculties: "ଫ୍ୟାକଲ୍ଟି ତାଲିକା",
    request: "ଅନୁରୋଧ",
    requests: "ଅନୁରୋଧଗୁଡ଼ିକ",
    complaint: "ଅଭିଯୋଗ",
    complaints: "ଅଭିଯୋଗସମୂହ",
    submitComplaint: "ଅଭିଯୋଗ ଦାଖଲ କରନ୍ତୁ",
    bonafideCertificate: "ବୋନାଫାଇଡ୍ ପ୍ରମାଣପତ୍ର",
    documents: "ଦସ୍ତାବିଜ୍ / ପ୍ରମାଣପତ୍ର",
    docRequest: "ପ୍ରମାଣପତ୍ର / ଫର୍ମ",
    gatePass: "ଗେଟ୍ ପାସ୍",
    more: "ଅଧିକ",
    leaveRequest: "ଛୁଟି ଅନୁରୋଧ",
    feeDuesQuery: "ଫିସ୍ / ବକେୟା ପ୍ରଶ୍ନ",
    pending: "ବିଚାରାଧୀନ",
    approved: "ଅନୁମୋଦିତ",
    inProgress: "ପ୍ରକ୍ରିୟାଧୀନ",
    resolved: "ସମାଧାନ ହୋଇଛି",
    confirmed: "ନିଶ୍ଚିତ ହୋଇଛି",
    confirmResolution: "ସମାଧାନ ନିଶ୍ଚିତ କରନ୍ତୁ",
    auditTrail: "ଅଡିଟ୍ ଟ୍ରେଲ୍ (କାର୍ଯ୍ୟକ୍ରମ ଇତିହାସ)",
    assignedStaff: "ନିଯୁକ୍ତ କର୍ମଚାରୀ",
    location: "ସ୍ଥାନ",

    // Progress Screen
    yourProgress: "ଆପଣଙ୍କ ପ୍ରଗତି 📊",
    academicJourney: "ଆପଣଙ୍କ ଶିକ୍ଷାଗତ ଯାତ୍ରା ଟ୍ରାକ୍ କରନ୍ତୁ",
    weeklyStudyTime: "ସାପ୍ତାହିକ ଅଧ୍ୟୟନ ସମୟ",
    classesAttended: "ଉପସ୍ଥିତ କ୍ଲାସ୍",
    testsTaken: "ଦିଆଯାଇଥିବା ପରୀକ୍ଷା",
    studyStreak: "ଅଧ୍ୟୟନ ଧାରା",
    subjectWiseProgress: "ବିଷୟ ଅନୁଯାୟୀ ପ୍ରଗତି",
    thisWeekActivity: "ଏହି ସପ୍ତାହର କାର୍ଯ୍ୟକଳାପ ସାରାଂଶ",

    // Schedule Screen
    yourSchedule: "ଆପଣଙ୍କ ସମୟ ସାରଣୀ 🗓️",
    manageTimetable: "ଦିନକୁ ସୁବିଧାରେ ପରିଚାଳନା କରନ୍ତୁ",
    addClass: "କ୍ଲାସ୍ ଯୋଡନ୍ତୁ",
    saveClass: "କ୍ଲାସ୍ ସେଭ୍ କରନ୍ତୁ",
    startTime: "ଆରମ୍ଭ ସମୟ",
    endTime: "ଶେଷ ସମୟ",
    room: "ରୁମ୍",
    facultyName: "ଶିକ୍ଷକ",
    completed: "ସମାପ୍ତ",
    ongoing: "ଚାଲୁଅଛି",
    upcoming: "ଆଗାମୀ",
    tomorrow: "ଆସନ୍ତାକାଲି",
    manageSubjects: "ବିଷୟ ପରିଚାଳନା",

    // Tasks Screen
    stayProductive: "ସକ୍ରିୟ ରୁହନ୍ତୁ 🛡️",
    neverMissDeadline: "ସମୟ ସୀମା ଭୁଲନ୍ତୁ ନାହିଁ",
    all: "ସମସ୍ତ",
    toDo: "କରିବାକୁ ଥିବା",
    addTask: "କାର୍ଯ୍ୟ ଯୋଡନ୍ତୁ",
    subject: "ବିଷୟ",
    due: "ଶେଷ ତାରିଖ",
    priority: "ଅଗ୍ରାଧିକାର",
    subtasks: "ଉପ-କାର୍ଯ୍ୟ",

    // Settings
    account: "ଖାତା",
    editProfile: "ପ୍ରୋଫାଇଲ୍ ସଂପାଦନ",
    password: "ପାସୱାର୍ଡ",
    changePassword: "ପାସୱାର୍ଡ ବଦଳାନ୍ତୁ",
    notifications: "ସୂଚନା",
    preferences: "ପସନ୍ଦ",
    theme: "ଥିମ୍",
    language: "ଭାଷା",
    college: "କଲେଜ",
    accountRole: "ଖାତା ଭୂମିକା",
    student: "ଛାତ୍ର",
    academicDetails: "ଶିକ୍ଷାଗତ ବିବରଣୀ",
    support: "ସହାୟତା",
    helpFaq: "ସାହାଯ୍ୟ ଏବଂ ପ୍ରଶ୍ନୋତ୍ତର",
    logout: "ଲଗ୍ ଆଉଟ୍",
    loggingOut: "ଲଗ୍ ଆଉଟ୍ ହେଉଛି...",
    chooseTheme: "ଥିମ୍ ବାଛନ୍ତୁ",
    chooseLanguage: "ଭାଷା ବାଛନ୍ତୁ",
    light: "ଲାଇଟ୍",
    dark: "ଡାର୍କ",
    system: "ସିଷ୍ଟମ୍",
    currentPassword: "ବର୍ତ୍ତମାନର ପାସୱାର୍ଡ",
    newPassword: "ନୂତନ ପାସୱାର୍ଡ",
    confirmPassword: "ନୂତନ ପାସୱାର୍ଡ ନିଶ୍ଚିତ କରନ୍ତୁ",
    passwordHint: "ପାସୱାର୍ଡ ଅତି କମରେ ୬ ଅକ୍ଷର ହେବା ଉଚିତ।",
    passwordMismatch: "ନୂତନ ପାସୱାର୍ଡ ଏବଂ ନିଶ୍ଚିତୀକରଣ ମେଳ ଖାଉନାହିଁ।",
    passwordWeak: "ନୂତନ ପାସୱାର୍ଡ ଅତି କମରେ ୬ ଅକ୍ଷର ହେବା ଉଚିତ।",
    passwordSame: "ନୂତନ ପାସୱାର୍ଡ ଅଲଗା ହେବା ଉଚିତ।",
    missingInfo: "ଦୟାକରି ସମସ୍ତ ଫିଲ୍ଡ ପୂରଣ କରନ୍ତୁ।",
    updating: "ଅପଡେଟ୍ ହେଉଛି...",
    forgotPasswordPrompt: "ବର୍ତ୍ତମାନର ପାସୱାର୍ଡ ଭୁଲିଗଲେ କି?",
    sendResetEmail: "ଇମେଲକୁ ରିସେଟ୍ ଲିଙ୍କ୍ ପଠାନ୍ତୁ",
    resetEmailSent: "ରିସେଟ୍ ଇମେଲ୍ ପଠାଗଲା",
    resetEmailSentDesc: "ଆପଣଙ୍କ ଇମେଲକୁ ଲିଙ୍କ୍ ପଠାଯାଇଛି।",
    passwordChangedSuccess: "ପାସୱାର୍ଡ ସଫଳତାର ସହିତ ଅପଡେଟ୍ ହୋଇଛି।",
    notLoggedIn: "ଆପଣ ଲଗ୍ ଇନ୍ ନାହାଁନ୍ତି।",
    learnConnectGrow: "ଶିଖନ୍ତୁ। ଯୋଡ଼ିହୁଅନ୍ତୁ। ବଢ଼ନ୍ତୁ।",
    collegeSubtext: "ଆପଣଙ୍କ କଲେଜ ଜୀବନ ପାଇଁ ସବୁକିଛି ଏକ ସ୍ଥାନରେ।",
    attendanceGood: "ଆପଣଙ୍କ ଉପସ୍ଥିତି ବହୁତ ଭଲ!",
    targetReached: "ଦୈନିକ ଲକ୍ଷ୍ୟର",
    cgpaStatus: "ସାମଗ୍ରିକ ପ୍ରଦର୍ଶନ",
    leaveGatepass: "ଛୁଟି / ଗେଟ୍ ପାସ୍",
    aiAssistant: "ଏଆଇ ସହାୟକ",
    messages: "ସନ୍ଦେଶ",
    specialNotes: "ବିଶେଷ ନୋଟ୍ ଏବଂ ଗୁରୁତ୍ୱପୂର୍ଣ୍ଣ ପ୍ରଶ୍ନ",
    specialNotesSub: "ଶିକ୍ଷକଙ୍କ ଦ୍ୱାରା ଦିଆଯାଇଥିବା ଗୁରୁତ୍ୱପୂର୍ଣ୍ଣ ପ୍ରଶ୍ନ ଓ ନୋଟ୍",
    teacherPortal: "ଶିକ୍ଷକ ପୋର୍ଟାଲ (ଆଇଡି ଏବଂ ପାସୱାର୍ଡ ଅପଡେଟ୍)",
    teacherConnection: "ଶିକ୍ଷକ ଏବଂ କ୍ଲାସରୁମ୍ ସଂଯୋଗ",
    connectTeacher: "ଶିକ୍ଷକଙ୍କ ସହିତ ଯୋଡ଼ିହୁଅନ୍ତୁ",
    teacherMessages: "ଶିକ୍ଷକ ସନ୍ଦେଶ ଏବଂ ଫଟୋ",
    attendanceStanding: "ଉପସ୍ଥିତି ଏବଂ ସ୍ଥିତି",
    studentInfo: "ଛାତ୍ର ବିବରଣୀ",
    degree: "ଡିଗ୍ରୀ",
    department: "ବିଭାଗ",
    semester: "ସେମିଷ୍ଟାର",
    section: "ସେକ୍ସନ",
    rollNo: "ରୋଲ୍ ନମ୍ବର",
    certificatesHonors: "ପ୍ରମାଣପତ୍ର ଏବଂ ସମ୍ମାନ",
    academicTimetable: "ଶିକ୍ଷାଗତ ସମୟସାରଣୀ",
    personalInfo: "ବ୍ୟକ୍ତିଗତ ସୂଚନା",
    fullName: "ପୂରା ନାମ",
    email: "ଇମେଲ୍",
    phoneNumber: "ଫୋନ୍ ନମ୍ବର",
  },
  te: {
    // Navigation & Tabs
    home: "హోమ్",
    progress: "పురోగతి",
    schedule: "షెడ్యూల్",
    tasks: "టాస్క్‌లు",
    profile: "ప్రొఫైల్",

    // Common
    settings: "సెట్టింగ్‌లు",
    search: "శోధించండి...",
    viewAll: "అన్నీ చూడండి",
    save: "సేవ్ చేయండి",
    cancel: "రద్దు చేయండి",
    delete: "తొలగించండి",
    loading: "లోడ్ అవుతోంది...",
    success: "విజయవంతం",
    error: "లోపం",

    // Home Dashboard
    welcomeBack: "స్వాగతం",
    services: "సేవలు",
    quickStats: "సత్వర గణాంకాలు",
    todaySchedule: "నేటి షెడ్యూల్",
    recentNotices: "తాజా నోటీసులు",
    attendance: "హాజరు",
    studyHours: "అధ్యయన గంటలు",
    assignments: "అసైన్‌మెంట్లు",
    cgpa: "సిజిపిఎ",
    tasksDone: "పూర్తయిన పనులు",

    // Services
    fees: "ఫీజులు",
    hostel: "హాస్టల్",
    mess: "మెస్",
    notice: "నోటీస్",
    notices: "నోటీసులు",
    report: "నివేదిక",
    reports: "నివేదికలు",
    faculty: "ఫ్యాకల్టీ",
    faculties: "ఫ్యాకల్టీ డైరెక్టరీ",
    request: "అభ్యర్థన",
    more: "మరిన్ని",

    // Progress Screen
    yourProgress: "మీ పురోగతి 📊",
    academicJourney: "మీ విద్యా ప్రయాణాన్ని ట్రాక్ చేయండి",
    weeklyStudyTime: "వారపు అధ్యయన సమయం",
    classesAttended: "హాజరైన తరగతులు",
    testsTaken: "రాసిన పరీక్షలు",
    studyStreak: "స్టడీ స్ట్రీక్",
    subjectWiseProgress: "సబ్జెక్ట్ వారీగా పురోగతి",
    thisWeekActivity: "ఈ వారం కార్యాచరణ సారాంశం",

    // Schedule Screen
    yourSchedule: "మీ షెడ్యూల్ 🗓️",
    manageTimetable: "మీ రోజును సమర్థవంతంగా నిర్వహించండి",
    addClass: "తరగతిని జోడించండి",
    saveClass: "తరగతిని సేవ్ చేయండి",
    startTime: "ప్రారంభ సమయం",
    endTime: "ముగింపు సమయం",
    room: "గది",
    facultyName: "ఫ్యాకల్టీ",
    completed: "పూర్తయింది",
    ongoing: "కొనసాగుతోంది",
    upcoming: "రాబోయేది",
    tomorrow: "రేపు",
    manageSubjects: "సబ్జెక్టులను నిర్వహించండి",

    // Tasks Screen
    stayProductive: "ఉత్పాదకంగా ఉండండి 🛡️",
    neverMissDeadline: "గడువును ఎప్పుడూ మిస్ అవ్వకండి",
    all: "అన్నీ",
    toDo: "చేయవలసినవి",
    inProgress: "పురోగతిలో ఉంది",
    addTask: "టాస్క్ జోడించండి",
    subject: "సబ్జెక్ట్",
    due: "గడువు తేదీ",
    priority: "ప్రాధాన్యత",
    subtasks: "ఉప-పనులు",

    // Settings
    account: "ఖాతా",
    editProfile: "ప్రొఫైల్ సవరించండి",
    password: "పాస్‌వర్డ్",
    changePassword: "పాస్‌వర్డ్ మార్చండి",
    notifications: "నోటిఫికేషన్‌లు",
    preferences: "ప్రాధాన్యతలు",
    theme: "థీమ్",
    language: "భాష",
    college: "కళాశాల",
    accountRole: "ఖాతా పాత్ర",
    student: "విద్యార్థి",
    academicDetails: "విద్యా వివరాలు",
    support: "మద్దతు",
    helpFaq: "సహాయం & తరచుగా అడిగే ప్రశ్నలు",
    logout: "లాగ్ అవుట్",
    loggingOut: "లాగ్ అవుట్ అవుతోంది...",
    chooseTheme: "థీమ్‌ను ఎంచుకోండి",
    chooseLanguage: "భాషను ఎంచుకోండి",
    light: "లైట్",
    dark: "డార్క్",
    system: "సిస్టమ్",
    currentPassword: "ప్రస్తుత పాస్‌వర్డ్",
    newPassword: "కొత్త పాస్‌వర్డ్",
    confirmPassword: "కొత్త పాస్‌వర్డ్‌ను నిర్ధారించండి",
    passwordHint: "పాస్‌వర్డ్ కనీసం 6 అక్షరాలు ఉండాలి.",
    passwordMismatch: "కొత్త పాస్‌వర్డ్ మరియు నిర్ధారణ సరిపోలడం లేదు.",
    passwordWeak: "కొత్త పాస్‌వర్డ్ కనీసం 6 అక్షరాలు ఉండాలి.",
    passwordSame: "కొత్త పాస్‌వర్డ్ భిన్నంగా ఉండాలి.",
    missingInfo: "దయచేసి అన్ని ఫీల్డ్‌లను పూరించండి.",
    updating: "నవీకరిస్తోంది...",
    forgotPasswordPrompt: "ప్రస్తుత పాస్‌వర్డ్ మర్చిపోయారా?",
    sendResetEmail: "ఇమెయిల్‌కు రీసెట్ లింక్‌ను పంపండి",
    resetEmailSent: "రీసెట్ ఇమెయిల్ పంపబడింది",
    resetEmailSentDesc: "మీ నమోదిత ఇమెయిల్‌కు లింక్ పంపబడింది.",
    passwordChangedSuccess: "మీ పాస్‌వర్డ్ విజయవంతంగా నవీకరించబడింది.",
    notLoggedIn: "మీరు లాగిన్ చేయలేదు.",
    learnConnectGrow: "నేర్చుకోండి. కనెక్ట్ అవ్వండి. ఎదగండి.",
    collegeSubtext: "మీ కళాశాల జీవితానికి అవసరమైనవన్నీ ఒకే చోట.",
    attendanceGood: "మీ హాజరు బాగుంది!",
    targetReached: "రోజువారీ లక్ష్యంలో",
    cgpaStatus: "మొత్తం ప్రదర్శన",
    leaveGatepass: "సెలవు / గేట్ పాస్",
    aiAssistant: "AI అసిస్టెంట్",
    messages: "సందేశాలు",
    specialNotes: "ప్రత్యేక గమనికలు మరియు ముఖ్యమైన ప్రశ్నలు",
    specialNotesSub: "అధ్యాపకులు పంచుకున్న ముఖ్యమైన పరీక్ష ప్రశ్నలు & గమనికలు",
    teacherPortal: "ఉపాధ్యాయ పోర్టల్ (ఐడి & పాస్‌వర్డ్ అప్‌డేట్)",
    teacherConnection: "ఉపాధ్యాయ & తరగతి గది కనెక్షన్",
    connectTeacher: "ఉపాధ్యాయుడితో కనెక్ట్ అవ్వండి",
    teacherMessages: "ఉపాధ్యాయుల సందేశాలు & ఫోటోలు",
    attendanceStanding: "హాజరు & విద్యా స్థితి",
    studentInfo: "విద్యార్థి సమాచారం",
    degree: "డిగ్రీ",
    department: "విభాగం",
    semester: "సెమిస్టర్",
    section: "సెక్షన్",
    rollNo: "రోల్ నంబర్",
    certificatesHonors: "సర్టిఫికెట్లు మరియు గౌరవాలు",
    academicTimetable: "విద్యా సమయ పట్టిక",
    personalInfo: "వ్యక్తిగత సమాచారం",
    fullName: "పూర్తి పేరు",
    email: "ఈమెయిల్",
    phoneNumber: "ఫోన్ నంబర్",
  },
  bn: {
    home: "হোম",
    progress: "অগ্রগতি",
    schedule: "সময়সূচী",
    tasks: "কার্যক্রম",
    aiAssistant: "এআই সহকারী",
    profile: "প্রোফাইল",
    settings: "সেটিংস",
    services: "সেবাসমূহ",
    quickStats: "পরিসংখ্যান",
    todaySchedule: "আজকের সময়সূচী",
    recentNotices: "সাম্প্রতিক বিজ্ঞপ্তি",
    attendance: "উপস্থিতি",
    studyHours: "অধ্যয়নের সময়",
    assignments: "অ্যাসাইনমেন্ট",
    cgpa: "সিজিপিএ",
    fees: "ফি",
    hostel: "হোস্টেল",
    mess: "মেস",
    notices: "বিজ্ঞপ্তি",
    reports: "প্রতিবেদন",
    faculty: "শিক্ষকবৃন্দ",
    more: "আরও",
    logout: "লগআউট",
    welcomeBack: "স্বাগতম",
    learnConnectGrow: "শিখুন। যুক্ত হন। এগিয়ে যান।",
    collegeSubtext: "কলেজ জীবনের সব সুবিধা এক জায়গায়।",
    attendanceGood: "আপনার উপস্থিতি খুব ভালো!",
    targetReached: "দৈনিক লক্ষ্যের",
    cgpaStatus: "সামগ্রিক ফলাফল",
    viewAll: "সব দেখুন",
    save: "সংরক্ষণ",
    cancel: "বাতিল",
    messages: "বার্তা",
    specialNotes: "বিশেষ নোট এবং গুরুত্বপূর্ণ প্রশ্ন",
    specialNotesSub: "শিক্ষক কর্তৃক প্রদত্ত গুরুত্বপূর্ণ প্রশ্ন ও নোট",
    teacherPortal: "শিক্ষক পোর্টাল (আইডি ও পাসওয়ার্ড আপডেট)",
    teacherConnection: "শিক্ষক এবং ক্লাসরুম সংযোগ",
    connectTeacher: "শিক্ষকের সাথে যুক্ত হন",
    teacherMessages: "শিক্ষকের বার্তা ও ছবি",
    attendanceStanding: "উপস্থিতি ও স্থিতি",
    studentInfo: "শিক্ষার্থী তথ্য",
    degree: "ডিগ্রি",
    department: "বিভাগ",
    semester: "সেমিস্টার",
    section: "সেকশন",
    rollNo: "রোল নম্বর",
    certificatesHonors: "সার্টিফিকেট ও সম্মাননা",
    academicTimetable: "একাডেমিক রুটিন",
    personalInfo: "ব্যক্তিগত তথ্য",
    fullName: "পুরো নাম",
    email: "ইমেইল",
    phoneNumber: "ফোন নম্বর",
  },
  ta: {
    home: "முகப்பு",
    progress: "முன்னேற்றம்",
    schedule: "அட்டவணை",
    tasks: "பணிகள்",
    aiAssistant: "AI உதவியாளர்",
    profile: "சுயவிவரம்",
    settings: "அமைப்புகள்",
    services: "சேவைகள்",
    quickStats: "விரைவு விவரங்கள்",
    todaySchedule: "இன்றைய அட்டவணை",
    recentNotices: "சமீபத்திய அறிவிப்புகள்",
    attendance: "வருகை",
    studyHours: "படிப்பு நேரம்",
    assignments: "படைப்புகள்",
    cgpa: "சிஜிபிஏ",
    fees: "கட்டணம்",
    hostel: "விடுதி",
    mess: "உணவகம்",
    notices: "அறிவிப்புகள்",
    reports: "அறிக்கைகள்",
    faculty: "ஆசிரியர்கள்",
    more: "மேலும்",
    logout: "வெளியேறு",
    welcomeBack: "வணக்கம்",
    learnConnectGrow: "கற்க. இணைய. வளர.",
    collegeSubtext: "கல்லூரி வாழ்க்கைக்கான அனைத்தும் ஒரே இடத்தில்.",
    attendanceGood: "உங்கள் வருகை நன்று!",
    targetReached: "இன்றைய இலக்கில்",
    cgpaStatus: "மொத்த செயல்திறன்",
    viewAll: "அனைத்தும் காண்க",
    save: "சேமி",
    cancel: "ரத்து செய்",
    messages: "செய்திகள்",
    specialNotes: "சிறப்பு குறிப்புகள் மற்றும் முக்கியமான கேள்விகள்",
    specialNotesSub: "ஆசிரியர்கள் பகிர்ந்த முக்கியமான தேர்வுக் குறிப்புகள்",
    teacherPortal: "ஆசிரியர் போர்டல் (ஐடி & கடவுச்சொல் மாற்றம்)",
    teacherConnection: "ஆசிரியர் & வகுப்பு இணைப்பு",
    connectTeacher: "ஆசிரியருடன் இணையுங்கள்",
    teacherMessages: "ஆசிரியர் செய்திகள் & புகைப்படங்கள்",
    attendanceStanding: "வருகை & நிலை",
    studentInfo: "மாணவர் தகவல்",
    degree: "பட்டம்",
    department: "துறை",
    semester: "பருவம்",
    section: "பிரிவு",
    rollNo: "பதிவு எண்",
    certificatesHonors: "சான்றிதழ்கள் & விருதுகள்",
    academicTimetable: "கல்வி கால அட்டவணை",
    personalInfo: "தனிப்பட்ட தகவல்",
    fullName: "முழு பெயர்",
    email: "மின்னஞ்சல்",
    phoneNumber: "தொலைபேசி எண்",
  },
  mr: {
    home: "होम",
    progress: "प्रगती",
    schedule: "वेळापत्रक",
    tasks: "कामे",
    aiAssistant: "एआय सहाय्यक",
    profile: "प्रोफाइल",
    settings: "सेटिंग्ज",
    services: "सेवा",
    quickStats: "महत्त्वाचे आकडे",
    todaySchedule: "आजचे वेळापत्रक",
    recentNotices: "ताजी सूचना",
    attendance: "उपस्थिती",
    studyHours: "अभ्यासाचे तास",
    assignments: "असाइनमेंट्स",
    cgpa: "सीजीपीए",
    fees: "शुल्क",
    hostel: "वसतिगृह",
    mess: "मेस",
    notices: "सूचना",
    reports: "अहवाल",
    faculty: "प्राध्यापक",
    more: "अधिक",
    logout: "लॉग आउट",
    welcomeBack: "स्वागत आहे",
    learnConnectGrow: "शिका. जोडा. प्रगती करा.",
    collegeSubtext: "कॉलेज जीवनासाठी लागणाऱ्या सर्व गोष्टी एकाच ठिकाणी.",
    attendanceGood: "तुमची उपस्थिती चांगली आहे!",
    targetReached: "दैनंदिन लक्ष्याचे",
    cgpaStatus: "एकूण कामगिरी",
    viewAll: "सर्व पहा",
    save: "जतन करा",
    cancel: "रद्द करा",
    messages: "संदेश",
    specialNotes: "विशेष नोट्स आणि महत्त्वाचे प्रश्न",
    specialNotesSub: "प्राध्यापकांनी दिलेले महत्त्वाचे परीक्षेचे प्रश्न व नोट्स",
    teacherPortal: "प्राध्यापक पोर्टल (आयडी व पासवर्ड अपडेट)",
    teacherConnection: "प्राध्यापक आणि वर्ग जोडणी",
    connectTeacher: "प्राध्यापकांशी जोडा",
    teacherMessages: "प्राध्यापकांचे संदेश आणि फोटो",
    attendanceStanding: "उपस्थिती आणि शैक्षणिक स्थिती",
    studentInfo: "विद्यार्थी माहिती",
    degree: "पदवी",
    department: "विभाग",
    semester: "सत्र / सेमिस्टर",
    section: "तुकडी / सेक्शन",
    rollNo: "रोल नंबर",
    certificatesHonors: "प्रमाणपत्रे आणि सन्मान",
    academicTimetable: "शैक्षणिक वेळापत्रक",
    personalInfo: "वैयक्तिक माहिती",
    fullName: "पूर्ण नाव",
    email: "ईमेल",
    phoneNumber: "फोन नंबर",
  },
  gu: {
    home: "હોમ",
    progress: "પ્રગતિ",
    schedule: "સમયપત્રક",
    tasks: "કાર્યો",
    aiAssistant: "AI સહાયક",
    profile: "પ્રોફાઇલ",
    settings: "સેટિંગ્સ",
    services: "સેવાઓ",
    quickStats: "ઝડપી આંકડા",
    todaySchedule: "આજનું સમયપત્રક",
    recentNotices: "તાજેતરની નોટિસ",
    attendance: "હાજરી",
    studyHours: "અભ્યાસના કલાકો",
    assignments: "અસાઇનમેન્ટ",
    cgpa: "સીજીપીએ",
    fees: "ફી",
    hostel: "હોસ્ટેલ",
    mess: "મેસ",
    notices: "સૂચનાઓ",
    reports: "અહેવાલ",
    faculty: "ફેકલ્ટી",
    more: "વધુ",
    logout: "લૉગ આઉટ",
    welcomeBack: "સ્વાગત છે",
    learnConnectGrow: "શીખો. જોડાઓ. પ્રગતિ કરો.",
    collegeSubtext: "કોલેજ જીવન માટેની બધી સુવિધાઓ એક જ સ્થળે.",
    attendanceGood: "તમારી હાજરી ઉત્તમ છે!",
    targetReached: "દૈનિક લક્ષ્યનું",
    cgpaStatus: "એકંદર પ્રદર્શન",
    viewAll: "બધા જુઓ",
    save: "સાચવો",
    cancel: "રદ કરો",
    messages: "સંદેશાઓ",
    specialNotes: "ખાસ નોંધો અને મહત્વપૂર્ણ પ્રશ્નો",
    specialNotesSub: "શિક્ષકો દ્વારા શેર કરેલ મહત્વપૂર્ણ પરીક્ષા પ્રશ્નો અને નોંધો",
    teacherPortal: "શિક્ષક પોર્ટલ (આઈડી અને પાસવર્ડ અપડેટ)",
    teacherConnection: "શિક્ષક અને ક્લાસરુમ કનેક્શન",
    connectTeacher: "શિક્ષક સાથે જોડાઓ",
    teacherMessages: "શિક્ષકના સંદેશાઓ અને ફોટા",
    attendanceStanding: "હાજરી અને શૈક્ષણિક સ્થિતિ",
    studentInfo: "વિદ્યાર્થી માહિતી",
    degree: "ડિગ્રી",
    department: "વિભાગ",
    semester: "સેમેસ્ટર",
    section: "સેક્શન",
    rollNo: "રોલ નંબર",
    certificatesHonors: "પ્રમાણપત્રો અને સન્માન",
    academicTimetable: "શૈક્ષણિક સમયપત્રક",
    personalInfo: "વ્યક્તિગત માહિતી",
    fullName: "પૂરું નામ",
    email: "ઈમેલ",
    phoneNumber: "ફોન નંબર",
  },
};

interface LanguageContextType {
  languageCode: string;
  languageName: string;
  setLanguage: (code: string) => Promise<void>;
  t: (key: string, defaultText?: string) => string;
}

const LANGUAGE_STORAGE_KEY = "@campusly_language";

const LanguageContext = createContext<LanguageContextType>({
  languageCode: "en",
  languageName: "English",
  setLanguage: async () => {},
  t: (key: string, defaultText?: string) => defaultText || key,
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({
  children,
}) => {
  const [languageCode, setLanguageCodeState] = useState<string>("en");

  useEffect(() => {
    const loadLanguage = async () => {
      try {
        const savedLang = await AsyncStorage.getItem(LANGUAGE_STORAGE_KEY);
        if (savedLang) {
          const matched =
            SUPPORTED_LANGUAGES.find(
              (l) => l.code === savedLang || l.name.toLowerCase() === savedLang.toLowerCase()
            );
          if (matched) {
            setLanguageCodeState(matched.code);
          }
        }
      } catch (err) {
        console.warn("Error loading language from storage:", err);
      }
    };
    loadLanguage();
  }, []);

  const setLanguage = async (codeOrName: string) => {
    const matched =
      SUPPORTED_LANGUAGES.find(
        (l) =>
          l.code === codeOrName ||
          l.name.toLowerCase() === codeOrName.toLowerCase() ||
          l.nativeName.toLowerCase() === codeOrName.toLowerCase()
      );
    const finalCode = matched ? matched.code : "en";
    setLanguageCodeState(finalCode);
    try {
      await AsyncStorage.setItem(LANGUAGE_STORAGE_KEY, finalCode);
    } catch (err) {
      console.warn("Error saving language to storage:", err);
    }
  };

  const currentOption =
    SUPPORTED_LANGUAGES.find((l) => l.code === languageCode) || SUPPORTED_LANGUAGES[0];

  const t = (key: string, defaultText?: string): string => {
    const dict = translations[languageCode] || translations.en;
    if (dict && dict[key]) {
      return dict[key];
    }
    const englishDict = translations.en;
    if (englishDict && englishDict[key]) {
      return englishDict[key];
    }
    return defaultText || key;
  };

  return (
    <LanguageContext.Provider
      value={{
        languageCode,
        languageName: currentOption.name,
        setLanguage,
        t,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
